### ISSUE TITLE
local echos for E2E start off in a new message state that looks like a normal message

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2081]
Before grey-on-white (which is a bug too - see #2080) they start off black-on-white, which makes them look like an unencrypted-non-echo

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk@3a1159ce12779ca389296bd12125708d9080dd6d

**Comment by richvdh** [comment]
uh, don't think it's fixed. `isSending` doesn't cover all the cases of local echo. Also, I'd much rather you looked at the event itself than the configuration of the room to determine if the event is encrypted.

**Comment by richvdh** [comment]
There are two cases for local echo: one is that the remote echo arrives before the /send completes; the other is that there is a gap between the /send completing and the remote echo arriving. You've got one and not the other: hence the inconsistent results between users.

**Comment by ara4n** [comment]
k, thanks. sorting...

**Comment by ara4n** [comment]
refixed in 0473b14
