### ISSUE TITLE
RTE does not dismiss emoji selector on message send

### ISSUE THREAD

**Issue by eternaleye** [vector-im/vector-web#2128]
Sending a message ending with `:P` results in the emoji selector remaining visible after message send

**Comment by ara4n** [comment]
i think this has been fixed?

**Comment by aviraldg** [comment]
Sorry, looks like there's still some work left here: this is still broken for forced completions.
