### ISSUE TITLE
Vector-web shows renamings as multiple joins

### ISSUE THREAD

**Issue by aliencq** [vector-im/vector-web#2572]
![selection_160](https://cloud.githubusercontent.com/assets/7108174/20239313/b21205c8-a90e-11e6-9d65-9bc1d0771b36.png)

**Comment by aliencq** [comment]
![selection_161](https://cloud.githubusercontent.com/assets/7108174/20246919/4c622a54-a9d2-11e6-8f45-245c86e4f49f.png)

**Comment by richvdh** [comment]
@lukebarnard1 presumably you know about this/are working on it

**Comment by lukebarnard1** [comment]
Yep: known bug and it was one of the regressions that should be fixed as of matrix-org/matrix-react-sdk#554

**Comment by aliencq** [comment]
554 is merged, but some events still broken:
![spectacle x13597](https://cloud.githubusercontent.com/assets/7108174/21450801/1d6af246-c90b-11e6-916a-0ee7224dc5a3.png)
![spectacle t13597](https://cloud.githubusercontent.com/assets/7108174/21450837/4b58ec8a-c90b-11e6-977a-873cea089932.png)

**Comment by richvdh** [comment]
raised a new issue as #2798, thanks
