### ISSUE TITLE
Joining a room from invite email sometimes fails with "Missing token" error

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#797]
see SYN-611

**Comment by Kegsay** [comment]
This should now be fixed.

**Comment by AmandineLP** [comment]
@Kegsay mentioned it was deployed but apparently it's not fixed

**Comment by Kegsay** [comment]
Been through this with Yuval today, and it really does work and is fixed. I suspect this is aggressive caching on some proxy servers, but I have no solid proof of this. He has confirmed that:

> Seems to be working for those who didn't try nor registered before.

And he invited one of my email addresses and I signed up no problem. Closing this until we can get something more for me to work with.

**Comment by AmandineLP** [comment]
Reproduced on vector-27791c06ee27-react-a2e50eb496f1-js-977e33f1bd5c (I guess: the version doesn't appear in the settings, so had to take it from another tab I refreshed)

Steps: open the link in a new tab; landed on the room as guest; click on join => missing token.
Note: another guest session was open in Chrome in parallel, which might be the problem, and when logging out everywhere in chrome, clicking on the link brought me to the registration page, so I'll keep the bug closed but will put logs for our records.

Logs from FF where the invite is coming from: (@Amandine:matrix.org):

> MatrixClient sync state => PREPARED bundle.js:83:31255
> MatrixClient sync state => SYNCING bundle.js:83:31255
> Event $14549532525334yJSwI:matrix.org already in timeline [object Object] bundle.js:49:3285
> Event $14549532525334yJSwI:matrix.org already in timeline [object Object] bundle.js:49:3285
> Original: {"join_rule":"invite","history_visibility":"shared","power_levels_changed":false,"tags_changed":false,"tags":{},"areNotifsMuted":false} bundle.js:88:9970
> New: {"name":"Amandines","topic":"Testing","join_rule":"invite","history_visibility":"shared","power_levels_changed":false,"tags_changed":false,"tags":{},"areNotifsMuted":false,"_loading":false} bundle.js:88:10016
> Performing 2 operations bundle.js:88:11190
> Event $14549532525334yJSwI:matrix.org already in timeline [object Object] bundle.js:49:3285
> Settings saved with 0 errors bundle.js:84:25476
> Event $14549532525334yJSwI:matrix.org already in timeline [object Object] bundle.js:49:3285
> Invite amandine4@mailinator.com to !CKtEqqYoCMMFgaLTOS:matrix.org - isEmail=true bundle.js:87:12183
> Bad ID to invite:  bundle.js:87:11459
> 
> Invite amandine14@mailinator.com to !CKtEqqYoCMMFgaLTOS:matrix.org - isEmail=true bundle.js:87:12183
> Bad ID to invite:  bundle.js:87:11459
> 
> Invite amandine17@mailinator.com to !CKtEqqYoCMMFgaLTOS:matrix.org - isEmail=true bundle.js:87:12183
> Invited amandine4@mailinator.com bundle.js:87:12268
> Invited amandine14@mailinator.com bundle.js:87:12268
> Invited amandine17@mailinator.com bundle.js:87:12268
> Event $14549532525334yJSwI:matrix.org already in timeline [object Object] bundle.js:49:3285
> erreur de syntaxe version:1:1
> Presence: unavailable bundle.js:82:31624
> 

Logs from chrome after opening the link from the invite email in a new tab:

> Guest: true
> bundle.js:27 Guest: true
> bundle.js:126 Not registering as guest; email invite.
> bundle.js:124 SyncApi.sync
> bundle.js:127 MatrixClient sync state => PREPARED
> bundle.js:127 Attempting to peek into room !CKtEqqYoCMMFgaLTOS:matrix.org?email=amandine14@mailinator.com
> bundle.js:127 MatrixClient sync state => SYNCING
> https://matrix.org/_matrix/client/api/v1/rooms/!CKtEqqYoCMMFgaLTOS%3Amatrix…QgPSB0cnVlCjAwMmZzaWduYXR1cmUgXnC9sHIRCUwYpw-55yKQkeiXtmuC-GGtHme20r80f7AK Failed to load resource: the server responded with a status of 400 (Bad Request)
> bundle.js:127 Failed to peek into room: e.exports.MatrixError(anonymous function) @ bundle.js:127
> matrix.org/_matrix/client/api/v1/join/!CKtEqqYoCMMFgaLTOS%3Amatrix.org%3Fem…PSB0cnVlCjAwMmZzaWduYXR1cmUgXnC9sHIRCUwYpw-55yKQkeiXtmuC-GGtHme20r80f7AK:1 POST https://matrix.org/_matrix/client/api/v1/join/!CKtEqqYoCMMFgaLTOS%3Amatrix.…QgPSB0cnVlCjAwMmZzaWduYXR1cmUgXnC9sHIRCUwYpw-55yKQkeiXtmuC-GGtHme20r80f7AK 403 (Forbidden)
